# Generated by Django 5.1.4 on 2025-08-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_shelf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
