# Generated by Django 5.2.3 on 2025-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_delete_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='for-books/default_cover.jpg', upload_to=''),
        ),
    ]
