# Generated by Django 5.2.3 on 2025-08-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='cover_picture',
        ),
    ]
