# Generated by Django 5.2.3 on 2025-08-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_bookreview_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='author',
            new_name='user',
        ),
    ]
