# Generated by Django 5.2.3 on 2025-08-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_created_at_book_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
